# Generated by Django 6.0.2 on 2026-02-15 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomeFantasia', models.CharField(max_length=255)),
                ('razaoSocial', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoPessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('cpfCnpj', models.CharField(max_length=64)),
                ('telefone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('uf', models.CharField(blank=True, max_length=8)),
                ('cep', models.CharField(blank=True, max_length=32)),
                ('logoUrl', models.URLField(blank=True)),
                ('chavePix', models.CharField(blank=True, max_length=128)),
                ('observacoesPadraoDoc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço')], max_length=16)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('precoBase', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidade', models.CharField(max_length=64)),
                ('codigoBarras', models.CharField(blank=True, max_length=128)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LancamentoFinanceiro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=8)),
                ('origemTipo', models.CharField(choices=[('OS', 'OS'), ('Orcamento', 'Orçamento'), ('Manual', 'Manual')], max_length=16)),
                ('origemId', models.CharField(blank=True, max_length=128, null=True)),
                ('dataCompetencia', models.DateField()),
                ('dataVencimento', models.DateField(blank=True, null=True)),
                ('dataPagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('formaPagamento', models.CharField(blank=True, max_length=64)),
                ('categoria', models.CharField(blank=True, max_length=128)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipoPessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2)),
                ('cpfCnpj', models.CharField(blank=True, max_length=64, null=True)),
                ('telefone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('bairro', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('uf', models.CharField(blank=True, max_length=8)),
                ('observacoes', models.TextField(blank=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=64)),
                ('dataEmissao', models.DateTimeField()),
                ('validadeDias', models.IntegerField()),
                ('status', models.CharField(choices=[('Emitido', 'Emitido'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado'), ('ConvertidoEmOS', 'ConvertidoEmOS')], max_length=32)),
                ('observacoes', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('itemCatalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.itemcatalogo')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=64)),
                ('dataAbertura', models.DateTimeField()),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Em andamento', 'Em andamento'), ('Aguardando peça', 'Aguardando peça'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], max_length=32)),
                ('equipamento', models.CharField(max_length=255)),
                ('defeitoRelatado', models.TextField(blank=True)),
                ('observacoesGerais', models.TextField(blank=True)),
                ('laudoTecnico', models.TextField(blank=True)),
                ('solucao', models.TextField(blank=True)),
                ('valorMaoDeObra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valorProdutos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os', to='api.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='orcamento',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='api.ordemservico'),
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataHora', models.DateTimeField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('Visita', 'Visita'), ('Retorno cliente', 'Retorno cliente'), ('Cobrança', 'Cobrança'), ('Entrega', 'Entrega'), ('Outro', 'Outro')], max_length=32)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], max_length=16)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='OSItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('valorUnitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('itemCatalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.itemcatalogo')),
                ('ordemServico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.ordemservico')),
            ],
        ),
    ]
